# Generated by Django 5.0.6 on 2024-07-23 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uti', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('related_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uti', models.CharField(max_length=64)),
                ('start_x', models.IntegerField()),
                ('start_y', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('content_plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da__alfiter.contentplugin')),
            ],
        ),
    ]
