# Generated by Django 5.0.6 on 2024-07-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da__alfiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screensection',
            name='title',
            field=models.CharField(default='No title', max_length=200),
        ),
        migrations.AlterField(
            model_name='screensection',
            name='uti',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
