# Generated by Django 5.0.6 on 2024-07-23 10:00

import da__alfiter.models
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da__alfiter', '0002_screensection_title_alter_screensection_uti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentplugin',
            name='related_file',
            field=models.FileField(upload_to=pathlib.PurePosixPath('/home/user-07/Desktop/alfiter/dp__alfiter/da__alfiter/content_plugin')),
        ),
        migrations.AlterField(
            model_name='screensection',
            name='height',
            field=models.IntegerField(default=da__alfiter.models.randint_c_1),
        ),
        migrations.AlterField(
            model_name='screensection',
            name='start_x',
            field=models.IntegerField(default=da__alfiter.models.randint_c_2),
        ),
        migrations.AlterField(
            model_name='screensection',
            name='start_y',
            field=models.IntegerField(default=da__alfiter.models.randint_c_2),
        ),
        migrations.AlterField(
            model_name='screensection',
            name='width',
            field=models.IntegerField(default=da__alfiter.models.randint_c_1),
        ),
    ]
