# Generated by Django 5.0.6 on 2024-07-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da__alfiter', '0003_alter_contentplugin_related_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentplugin',
            name='related_file',
            field=models.FileField(upload_to='content_plugins/'),
        ),
    ]
