# Generated by Django 5.0.6 on 2024-07-23 12:40

import da__alfiter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da__alfiter', '0004_alter_contentplugin_related_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentplugin',
            name='related_file',
            field=models.FileField(upload_to=da__alfiter.models.unnanmed_function),
        ),
    ]
