# Generated by Django 5.0.6 on 2024-07-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da__alfiter', '0005_alter_contentplugin_related_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentplugin',
            name='related_file',
            field=models.FileField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uti', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(default='no title', max_length=200)),
                ('sections', models.ManyToManyField(to='da__alfiter.screensection')),
            ],
        ),
    ]
