# Generated by Django 5.0.6 on 2024-08-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da__alfiter', '0006_alter_contentplugin_related_file_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOfCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uti', models.CharField(max_length=64, unique=True)),
                ('images', models.ManyToManyField(to='da__alfiter.imageofcollection')),
            ],
        ),
    ]
