# Generated by Django 5.0.6 on 2024-08-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da__alfiter', '0007_imageofcollection_imagecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageofcollection',
            name='title',
            field=models.CharField(default='no title', max_length=128),
        ),
    ]
